from __future__ import annotations

from deepresearch_agent.schemas import DegradationRecord, Evidence, TaskNode


class DegradationManager:
    """Create fallback evidence and records for degraded research tasks."""

    def create_fallback_evidence(self, task: TaskNode, reason: str) -> Evidence:
        return Evidence(
            id=f"{task.id}_degraded_evidence",
            task_id=task.id,
            title=f"Degraded evidence for {task.name}",
            content=(
                "This evidence was generated by degraded fallback because the "
                "original research task failed or timed out."
            ),
            source_url=f"mock://degraded/{task.id}",
            confidence=0.5,
            metadata={"degraded": True, "reason": reason},
        )

    def create_record(
        self,
        task: TaskNode,
        reason: str,
        fallback_evidence: Evidence | None,
    ) -> DegradationRecord:
        return DegradationRecord(
            task_id=task.id,
            reason=reason,
            original_state=task.state,
            fallback_evidence_id=fallback_evidence.id if fallback_evidence else None,
        )
